export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_USERS_LIST = 'FETCH_USERS_LIST';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';
export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS';